### ISSUE TITLE
Edges aren't smooth.

### ISSUE THREAD

**Issue by ShaneQi** [HarshilShah/ActivityRings#12]
I attached 2 screenshots of my app. If you open them, you can tell that the edges of rings aren't smooth. And it's obvious on real devices. I thought it's because the rings are small (18 * 18 points in Screenshot 1), but even I set the size to 100 * 100 points (in screenshot 2), the issue is still visible to eyeballs on real devices.

I read through the source code, and I think it's a constraint of SpriteKit. But the gif in README.md seems smooth to me (because the gif is compressed?). 

|Screenshot 1|Screenshot 2|
|:---:|:---:|
|![img_5008](https://user-images.githubusercontent.com/7324708/50060338-4cdfdc80-0158-11e9-9636-7ac7028ace54.png)|![simulator screen shot - iphone xs - 2018-12-16 at 17 26 34](https://user-images.githubusercontent.com/7324708/50060342-59fccb80-0158-11e9-8171-170b7ece40db.png)|

**Comment by HarshilShah** [comment]
Hey there, thank you for opening an issue, and sorry for the late response.

If you’re still running into this issue, could you please tell me the version you’re having this issue on? I think this might be due to having multiple rings onscreen which the system tends not to handle well. The example GIF was taken from the macOS app which might be why its better rendered.

**Comment by ShaneQi** [comment]
Hey, thanks for responding!

I updated the pod to the latest version, and the rings became perfect. So I'm closing the issue.

I wouldn't keep this issue open if I knew a simple update will fix it. Sorry about that.

|before|after|
|:---:|:---:|
|![eJ8LgBmtSGCHjjyc82eXKA_thumb_2d52](https://user-images.githubusercontent.com/7324708/64079491-a61f7a00-ccad-11e9-8558-14be15dd8aa0.jpg)|![6n12XWYqT4KzrrGXXH7GIg_thumb_2d51](https://user-images.githubusercontent.com/7324708/64079467-796b6280-ccad-11e9-8d8a-281bc7b66ef8.jpg)|

**Comment by HarshilShah** [comment]
Awesome, that is good to know!
