### ISSUE TITLE
Please tell me how to set text in ActivityRings......

### ISSUE THREAD

**Issue by pontachandazo** [HarshilShah/ActivityRings#13]
I don't know .....
Below, my coding

`var sceneMapping = [WKInterfaceSKScene: ActivityRingScene]()
    @IBOutlet var ring: WKInterfaceSKScene!
    
    var label: SKLabelNode!
    

    @IBOutlet var button: WKInterfaceButton!
    override func awake(withContext context: Any?) {
        super.awake(withContext: context)
        button.setTitle("リングを動かす")
        label = SKLabelNode()
        
    }
    
    override func willActivate() {
        super.willActivate()
        
        sceneMapping[ring]  = ActivityRingScene(size: CGSize(width: 100, height: 100))
        
        label.text = "20:40"
        label.color = UIColor.white
        
        for (interfaceScene, ringScene) in sceneMapping {
            interfaceScene.presentScene(ringScene)
            ringScene.animateProgress(to: 0.75, withDuration: 2.0)
            ringScene.ringWidth = 8
        }
    }
    
    override func didDeactivate() {
        super.didDeactivate()
    }
    
    //buttonを押した時のメソッド
    @IBAction func buttonTapped() {
        print("設定ボタンが押されました")
        for (interfaceScene, ringScene) in sceneMapping {
            interfaceScene.presentScene(ringScene)
            ringScene.animateProgress(to: 0.5, withDuration: 0.5)
            ringScene.ringWidth = 8
        }
        
    }`

Please check and tell me................

**Comment by calda** [comment]
I added a label at the WatchKit-level. You can put the scene inside a `WKInterfaceGroup` and then center the `WKInterfaceLabel` (or `WKInterfaceTimer` in my case) in the center of that group:

<img width="820" alt="screen shot 2019-01-19 at 10 46 09 am" src="https://user-images.githubusercontent.com/1811727/51428947-808aa800-1bd7-11e9-958e-b234d3e69423.png">

Result:

![en_3](https://user-images.githubusercontent.com/1811727/51428966-ae6fec80-1bd7-11e9-9679-68c6a8837056.PNG)

**Comment by calda** [comment]
Although in the sample code you provided, it looks like you just aren't adding the `SKLabelNode` to your `interfaceScene`.

**Comment by HarshilShah** [comment]
Closing this as the problem seems to be resolved.
