### ISSUE TITLE
Unable to reference ActivityRingView

### ISSUE THREAD

**Issue by zayh** [HarshilShah/ActivityRings#7]
I installed ActivityRings via CocoaPods. My project is a phone app with a watch extension. When I attempt to reference ActivityRingView in the phone app's main view controller, I get the following warning:

<img width="798" alt="screen shot 2018-10-18 at 10 26 33 pm" src="https://user-images.githubusercontent.com/93079/47199765-058bca00-d328-11e8-9c76-06193e14d3d3.png">

**Comment by HarshilShah** [comment]
Hi there, thanks for opening an issue.

Could you try using the [`compilation-conditions` branch](https://github.com/HarshilShah/ActivityRings/tree/compilation-conditions) and let me know if that works?

**Comment by HarshilShah** [comment]
Fixed in #8
