### ISSUE TITLE
Ring isn't anti-aliased on watchOS

### ISSUE THREAD

**Issue by calda** [HarshilShah/ActivityRings#9]
<img width="380" alt="screen shot 2018-10-24 at 8 48 00 am" src="https://user-images.githubusercontent.com/1811727/47431290-8522fa00-d769-11e8-9d61-b9402256a10b.png">

Rings aren't appearing anti-aliased on watchOS. Are they anti-aliased on iOS? 

Is this a bug where the anti-aliasing isn't working on watchOS, or is just the incredibly-small-size making it more obvious that it isn't anti-aliased?

`SKShapeNode` does have an `isAntialiased` property, but that's enabled. My hunch is that this has something to do with the custom shader (that generates the gradient?)

**Comment by calda** [comment]
Interestingly, it looks fine at `progress = 0` but then un-anti-aliases when moved to `progress = 0.5`.

![img_6999](https://user-images.githubusercontent.com/1811727/47431774-b64ffa00-d76a-11e8-9972-2a9260759f9c.PNG) ![img_7002](https://user-images.githubusercontent.com/1811727/47431776-b819bd80-d76a-11e8-814d-7cb5aa52ecd6.PNG)

(Images from a real device this time)

**Comment by HarshilShah** [comment]
Yikes, that is pretty damn bad. I’d seen some issues on iOS but nowhere near as close to that. You’re right in that the shader is the issue; I’m using a `strokeShader` and setting the `lineWidth` to > 1, there will be some artifacts per [Apple’s docs](https://developer.apple.com/documentation/spritekit/skshapenode/1519885-linewidth): 

> A line width larger than 2.0 may cause rendering artifacts in the final rendered image. The default value is 1.0.

Apparently [disabling antialiasing](http://adampreble.net/blog/2015/02/a-quick-fix-for-fuzzy-skshapenode-lines/) might help, could you try that? (I don’t have a watchOS device to test with)

Other than that, I’m not quite sure how to fix this. Using a `fillShader` to colour a circle (thereby avoiding the lineWidth artifacts entirely) and masking it is one potential solution that might be worth exploring.

**Comment by calda** [comment]
I'll bang on it tomorrow morning and see what I can do 

(also it does look the same on both the simulator and on a physical device, from what I've seen)

**Comment by calda** [comment]
`SKCropNode` to the rescue!
<img width="872" alt="screen shot 2018-10-25 at 8 12 57 am" src="https://user-images.githubusercontent.com/1811727/47499382-d2689f80-d82d-11e8-99c4-5af237a74098.png">

**Comment by calda** [comment]
Fixed in #10
